export interface Topic {
  id: string;
  title: string;
  description: string;
  category: "Aqeedah" | "Fiqh" | "Seerah" | "Ibadah" | "Quran" | "Akhlaq";
  difficulty: 1 | 2 | 3;
  prerequisites: string[];
  resource: {
    title: string;
    source: string;
    url: string;
  };
}

export interface UserProgress {
  userId: string;
  completedTopicIds: string[];
  diagnosticAnswers: Record<string, string>;
  startedAt: string;
}

export interface DiagnosticQuestion {
  id: string;
  question: string;
  options: string[];
}

export type NodeStatus = "locked" | "unlocked" | "completed";

export interface RoadmapNode {
  topicId: string;
  status: NodeStatus;
  title: string;
  description: string;
  category: Topic["category"];
  difficulty: Topic["difficulty"];
}

export interface RoadmapResponse {
  nodes: RoadmapNode[];
  connections: [string, string][];
}

export interface CompleteTopicResponse {
  nodes: RoadmapNode[];
  connections: [string, string][];
  newlyUnlocked: string[];
}

// ── Clarity Cards ───────────────────────────────────────────────────────────
// Human-authored, sourced answers. The AI never composes this content; it only
// routes a free-text question to the best-matching card (or defers to a scholar).

export interface ClaritySource {
  title: string;
  source: string;
  url: string;
}

export interface ClarityDifference {
  /** The school(s) or view this position belongs to, e.g. "Hanafi". */
  label: string;
  detail: string;
}

export interface ClarityCard {
  id: string;
  question: string;
  /** Alternate phrasings used by the keyword fallback matcher. */
  aliases: string[];
  category: Topic["category"];
  summary: string;
  /** The ijma' core — what all mainstream Muslims agree on. */
  agreed: string;
  /** Where the schools differ, stated factually, never as a ruling. */
  differences: ClarityDifference[];
  /** Optional compassionate note aimed at reverts. */
  reassurance?: string;
  whoToAsk: string;
  sources: ClaritySource[];
}

export interface ClarityAskResponse {
  /** The matched human-authored card, or null when nothing fit. */
  card: ClarityCard | null;
  /** True when the question seeks a personal ruling we must defer to a scholar. */
  deferToScholar: boolean;
  /** A short, safe framing message shown above the card. */
  message: string;
}

// ── Masjid Bridge ─────────────────────────────────────────────────────────────
// Real-world connection: a curated directory, deterministic etiquette guidance,
// and human-triaged connection requests. None of this is generated by an LLM.

export interface Masjid {
  id: string;
  name: string;
  city: string;
  area: string;
  revertFriendly: boolean;
  newMuslimClass: boolean;
  womensFacility: boolean;
  languages: string[];
  note: string;
  website: string;
  /** False for the hand-seeded sample dataset; true once a listing is verified. */
  verified: boolean;
}

export interface EtiquetteSection {
  id: string;
  title: string;
  points: string[];
}

export type ConnectType = "buddy" | "mentor" | "visit";

/** A request a real person on the team follows up on — not a bot reply. */
export interface ConnectRequest {
  id: string;
  userId: string;
  name: string;
  city: string;
  contactMethod: string;
  type: ConnectType;
  message: string;
  createdAt: string;
}

// ── Prayer times (real data via Aladhan) ───────────────────────────────────────
// Live, time-sensitive data pulled from a real external API — never mocked.

export interface PrayerTimings {
  Fajr: string;
  Sunrise: string;
  Dhuhr: string;
  Asr: string;
  Maghrib: string;
  Isha: string;
}

export interface PrayerTimesResult {
  city: string;
  country: string;
  /** IANA timezone the timings belong to, e.g. "Europe/London". */
  timezone: string;
  gregorianDate: string;
  hijriDate: string;
  method: string;
  timings: PrayerTimings;
}
